# -*- coding: utf-8 -*-
"""Projeto.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1DnUKljoGYGwLP1No5vBR9Kk7Haca1Qvu
"""

valores_extrato = {} #dicionário para armazenar a data e o valor do depósito
quantidade_saque = 0
saldo = 0

#Depósito
auxiliar = 0 #variável que sai do laço se o valor digitado for positivo

while auxiliar == 0:

  deposito = float(input("Digite o valor a ser depositado:"))

  if deposito > 0:
    valores_extrato.append{(date.today(), deposito)}
    saldo = saldo + deposito
    auxiliar = 1
  else:
    print("O valor digitado não é válido")

#Saque
auxiliar = 0 #variável que sai do laço se o valor digitado for positivo

while quantidade_saque < 3:

  while auxiliar == 0:
    saque = float(input("Digite o valor a ser sacado:"))

    if 0 < saque <= 500:
      saque = saque * -1
      saldo = saldo + saque
      valores_extrato.append{(date.today(), saque)}
      quantidade_saque = quantidade_saque + 1
      auxiliar = 1
    else:
      print("O valor digitado não é válido")

else:
  print("Você pode fazer até 3 saques diários")

#Extrato
for i in valores_extrato:
  print(valores_extrato{i}\n)